# Generated by Django 6.0.2 on 2026-03-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Buyer", "0005_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="fees_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_cents",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
