# Generated by Django 6.0.2 on 2026-03-26 02:38

from django.db import migrations, models


def _sqlite_orderitem_columns(schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("PRAGMA table_info(Buyer_orderitem)")
        return {row[1] for row in cursor.fetchall()}


def forward_add_denorm_fields(apps, schema_editor):
    """Add title/author only if missing (handles SQLite DBs that already had a stray title column)."""
    OrderItem = apps.get_model("Buyer", "OrderItem")
    if schema_editor.connection.vendor == "sqlite":
        cols = _sqlite_orderitem_columns(schema_editor)
        if "author" not in cols:
            schema_editor.add_field(
                OrderItem,
                OrderItem._meta.get_field("author"),
            )
        if "title" not in cols:
            schema_editor.add_field(
                OrderItem,
                OrderItem._meta.get_field("title"),
            )
        return
    schema_editor.add_field(OrderItem, OrderItem._meta.get_field("author"))
    schema_editor.add_field(OrderItem, OrderItem._meta.get_field("title"))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("Buyer", "0006_order_tax_fees"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="orderitem",
                    name="author",
                    field=models.CharField(default="", max_length=255),
                ),
                migrations.AddField(
                    model_name="orderitem",
                    name="title",
                    field=models.CharField(default="", max_length=255),
                ),
            ],
            database_operations=[
                migrations.RunPython(forward_add_denorm_fields, noop_reverse),
            ],
        ),
    ]
