# Generated by Django 6.0.2 on 2026-03-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0005_paymentmethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='card_last4',
            new_name='last4',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='created_at',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='cardholder',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='brand',
            field=models.CharField(max_length=30),
        ),
    ]
