# Generated by Django 6.0.2 on 2026-03-26 02:44

from django.db import migrations, models


def _sqlite_orderitem_columns(schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("PRAGMA table_info(Buyer_orderitem)")
        return {row[1] for row in cursor.fetchall()}


def forward_add_deposit_required(apps, schema_editor):
    OrderItem = apps.get_model("Buyer", "OrderItem")
    if schema_editor.connection.vendor == "sqlite":
        cols = _sqlite_orderitem_columns(schema_editor)
        if "deposit_required" not in cols:
            schema_editor.add_field(
                OrderItem,
                OrderItem._meta.get_field("deposit_required"),
            )
        return
    schema_editor.add_field(
        OrderItem,
        OrderItem._meta.get_field("deposit_required"),
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("Buyer", "0007_orderitem_title_author"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="orderitem",
                    name="deposit_required",
                    field=models.BooleanField(default=False),
                ),
            ],
            database_operations=[
                migrations.RunPython(forward_add_deposit_required, noop_reverse),
            ],
        ),
    ]
