# Generated by Django 6.0.2 on 2026-03-22 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0007_book_remove_order_steward_contribution_and_more'),
        ('General', '0009_clear_book_cover_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='General.book'),
        ),
    ]
