# Generated by Django 6.0.2 on 2026-03-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0008_alter_orderitem_book'),
        ('Buyer', '0009_orderitembooksnapshot_ordershippingaddress'),
    ]

    operations = [
    ]
