# Generated by Django 6.0.2 on 2026-03-22 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0010_merge_20260322_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordershippingaddress',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordershippingaddress',
            name='source_address',
        ),
        migrations.DeleteModel(
            name='OrderItemBookSnapshot',
        ),
        migrations.DeleteModel(
            name='OrderShippingAddress',
        ),
    ]
