# Generated by Django 6.0.2 on 2026-03-22 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0011_remove_ordershippingaddress_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Payment_method',
            new_name='payment_method',
        ),
    ]
