# Generated by Django 6.0.2 on 2026-04-21 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0015_review'),
        ('General', '0013_user_seller_approved_user_seller_approved_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='order',
        ),
        migrations.RemoveField(
            model_name='review',
            name='seller',
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='General.book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Buyer.orderitem'),
        ),
    ]
