# Generated by Django 6.0.2 on 2026-02-27 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0002_book_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StewardContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_name', models.CharField(max_length=120)),
                ('contributor_city', models.CharField(max_length=120)),
                ('amount_cents', models.PositiveIntegerField()),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('steward_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.user')),
            ],
        ),
    ]
