# Generated by Django 6.0.2 on 2026-02-27 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='seller_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='General.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('steward', 'Steward'), ('seller', 'Seller'), ('admin', 'Admin')], max_length=20),
        ),
    ]
