# Generated by Django 6.0.2 on 2026-03-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0007_alter_user_groups_alter_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('admin', 'Admin')], max_length=20),
        ),
    ]
