# Generated by Django 6.0.2 on 2026-03-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0012_steward_pool_and_user_free_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seller_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='seller_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
