# Generated by Django 6.0.2 on 2026-04-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0013_user_seller_approved_user_seller_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_answer_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='security_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
