# Generated by Django 5.2.12 on 2026-04-22 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0014_user_buyer_approved_user_buyer_approved_at'),
        ('General', '0014_user_security_answer_hash_user_security_question'),
    ]

    operations = [
    ]
