
server {
    listen 80 default_server;
    server_name 34.226.244.102;
    location = /favicon.ico { access_log off; log_not_found off; }
    # Must match STATIC_URL (/static/) and STATIC_ROOT (…/staticfiles); collectstatic writes here.
    location /static/ {
        alias /home/ubuntu/software_eng_class_project/assets/;
    }
    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
}